#8: Step 5 (closes #8)
buildo/app-rpsosa pull request #12
Opened 2018-07-12 16:53 UTC by raasoft

Closes #8

## Test Plan

### tests performed

> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.

### tests not performed (domain coverage)

> At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has been tested.

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.

2018-07-12 17:04 UTC, gabro requested changes
Good start! There's room for improvement on the data types, but overall is looking nice 👍

2018-07-12 17:04 UTC, gabro commented on build.sbt
> +    "de.heikoseeberger" %% "akka-http-circe" % "1.21.0"),
minor, but this is not well formatted (you may want to setup scalafmt, let's discuss it tomorrow)

2018-07-12 17:04 UTC, gabro commented on src/main/scala/rps/Game.scala
> +        Some(RPSResponse(CaseEnumSerialization[RPSMove].caseToString(userMove), CaseEnumSerialization[RPSMove].caseToString(computerMove), outcome))
If you end up doing

```scala
x match {
  case None => None
  case Some(x) => Some(f(x))
}
```

you can use `.map` instead:

```scala
x.map(f)
```

2018-07-12 17:04 UTC, gabro commented on src/main/scala/rps/Game.scala
> +        Some(RPSResponse(CaseEnumSerialization[RPSMove].caseToString(userMove), CaseEnumSerialization[RPSMove].caseToString(computerMove), outcome))
IIRC you can do `RPSMove.caseToString(userMove)`, but you don't need any of this. See my comment below.

2018-07-12 17:04 UTC, gabro commented on src/main/scala/rps/Main.scala
> +                case None => complete("")
This is ok for now, but it's not pretty ;)
We'll see how to return a meaningful error instead.

2018-07-12 17:04 UTC, gabro commented on src/main/scala/rps/model/Request.scala
> +case class RPSRequest(userMove: String)
missing newline, I would suggest to configure this in vscode

2018-07-12 17:04 UTC, gabro commented on src/main/scala/rps/model/Response.scala
> +case class RPSResponse(userMove: String, computerMove: String, result: String)
String, String, String... Have you tried to use `Move` and `Result` instead? :)

2018-07-12 17:04 UTC, gabro commented on src/main/scala/rps/Game.scala
> +      case default => "Lose"
These strings look really like an enum :P

2018-07-13 09:10 UTC, raasoft commented
I still need to understand some "magic" about how a data type can be decoded to json if the case class is made up by enumero enumerators instead of strings (I can guess the enumero integration with circe is doing the trick but I don't understand how) and I still don't fully understand the magic behind 

```scala
entity(as[Request])
```

but we are going to see it on monday.

2018-07-13 09:17 UTC, gabro commented
@raasoft your intuition is right and the mechanism is the same of both your doubts. We'll talk about it on Monday.

2018-07-13 10:53 UTC, gabro requested changes
Almost there, nice job!

2018-07-13 10:53 UTC, gabro commented on src/main/scala/rps/Game.scala
> +    Random.shuffle(Set(Rock, Paper, Scissors)).head
This is now an enum, so you can do `Move.values` ;)

2018-07-13 10:53 UTC, gabro commented on src/main/scala/rps/Game.scala
> +      case default                                              => Lose
no need to bind `default` here, you can use `_` to avoid binding an identifier.

2018-07-13 10:53 UTC, gabro commented on src/main/scala/rps/model/Request.scala
> +case class Request(userMove: String)
This doesn't need to be a `String`

Hint: this will cause you to rewrite and remove a bunch of code :P

2018-07-13 10:53 UTC, gabro commented on src/main/scala/rps/model/Response.scala
> +import Result._
These imports are not needed

2018-07-13 10:53 UTC, gabro commented on build.sbt
> +    resolvers ++= Seq(Resolver.bintrayRepo("hseeberger", "maven"),
minor: you shouldn't need the `Resolver.bintrayRepo("hseeberger", "maven")` resolver

2018-07-13 13:27 UTC, gabro approved these changes
👍 nice job handling the error!

2018-07-13 13:29 UTC, merged